### ISSUE TITLE
[BUG] The audio of a level's cutscene will continue to play through ENDDOOM if the game is exited while it's playing.

### ISSUE THREAD

**Issue by Acts19quiz** [ZDoom/gzdoom#1816]
### GZDoom version

GZDoom 4.9.0

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 LTSC 21H2

### Relevant hardware info

Intel 6700k, NVIDIA GeForce 980Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

On cutscenes that don't automatically wipe to the startup when pressing Esc., if you exit the game while the cutscene is playing, the audio will continue to play out in the ENDDOOM display. Nothing else seems to happen once the audio finishes.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Script a cutscene (basically, anything other than a GameInfo intro).
2. Make sure ENDDOOM is set to display.
3. While it's playing, try to exit the game with Esc. (curiously, F7 and F10 go to the wipe like with the GameInfo case).

[Here is a small movie file](https://github.com/ZDoom/gzdoom/files/10016549/SMKintro.zip) to assist with reproduction. It's set to trigger the cutscene at E1M2's intro. IWAD can be any combination of doom.wad, chex.wad, or chex3.wad.

**Comment by coelckers** [comment]
fixed in eb97346b0e96a63c472b08b63277b403978f06b0

**Comment by Acts19quiz** [comment]
Did the above commit make it into https://github.com/ZDoom/gzdoom/commit/75da94aecd9b1c4c2e16b449dea1b9f9838c1af2 a.k.a. g4.10.0? I'm still experiencing the issue in the release build.
