### ISSUE TITLE
[BUG] GZDoom v 4.10.0 Quicksave rotation not working

### ISSUE THREAD

**Issue by sebastianpanetta** [ZDoom/gzdoom#2005]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Pro Version 2004 (OS Build 19041.1237)

### Relevant hardware info

Not relevant

### Have you checked that no other similar issue already exists?

- [ ] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Quicksave rotation is not working. When quicksaving with quicksave rotation enabled it just overwrites the same save slot without applying a rotation like in previous versions.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load a map
2. Quicksave

**Comment by CandiceJoy** [comment]
I cannot reproduce this in my dev environment (MacOS).

**Comment by CandiceJoy** [comment]
It looks like this was fixed https://asuna.candicejoy.com:7080/github.com/ZDoom/gzdoom/-/commit/854c57611fad48daf552bedefd3a915328a72b38?visible=1

**Comment by sebastianpanetta** [comment]
@CandiceJoy Hi, I did see that commit, but the bug is still present on version 4.10.0. Here's a video: https://drive.google.com/file/d/1PWAIDrMChpFHqY_z26B9lSO53-COSwJx/view?usp=sharing. Please can you open the issue again?

**Comment by CandiceJoy** [comment]
The bug was fixed after 4.10.0 came out, so of course it's not going to be in 4.10 xP

**Comment by sebastianpanetta** [comment]
Oh, sorry! My bad, I've just seen the g4.11pre tag. Thank you
