### ISSUE TITLE
[BUG] Teleports broken in versions newer than 4.11.3

### ISSUE THREAD

**Issue by nickbailuc** [ZDoom/gzdoom#2868]
### GZDoom version

4.14.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Please describe your specific OS version

Debian 13 (trixie)

### Relevant hardware info

Apple M2

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

After filing #2830 , I realized this is not just for silent teleports in `myhouse.pk3` but for regular teleports in vanilla Doom. I tested the original doom2.wad, the BFG doom2.wad, enhanced doom2.wad, and kex doom2.wad. Walking into a teleport does not trigger them immediately, but instead keeps you in the same location usually. Walking back and fourth through them, or with momentum sometimes randomly does trigger the teleport, but this seems to happen entirely random.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch any vanilla Doom2 wad (original, BFG, enhanced, kex)
2. Go to MAP04
3. Walk through the teleporters in the end of the map

### Your configuration

```ini
completely vanilla config, not even key bindings
```

**Comment by JeodC** [comment]
Hi, came across this error when testing various mods. I can confirm on linux arm64 teleports will only function if you are sprinting as you hit them. Normal player movement does not trigger them.

**Comment by nickbailuc** [comment]
> Hi, came across this error when testing various mods. I can confirm on linux arm64 teleports will only function if you are sprinting as you hit them. Normal player movement does not trigger them.

I have `always run` activated, but I guess even then it needs a certain speed (although I remember sometimes it works at a low speed randomly too). In any case this is bad in the vanilla games and ruins any silent teleport WADs.

I just use `g4.11.3` because it's the last version that worked properly, so definitely something changed in the newer versions that created this bug.

Any idea why this is happening specifically in `linux-arm64`, and what other architectures it may be happening on?

**Comment by JeodC** [comment]
Tick rate differences, especially in physics. I am able to make a teleport function with standard player speed by sliding back and forth very short distances while colliding with the teleport. It may be something in this section: https://github.com/ZDoom/gzdoom/blob/98b5d8b1d2333117364659f37dd18ace3230c717/src/playsim/p_teleport.cpp#L684-L785

..or I could be off track with my guess.

**Comment by grobuzga** [comment]
I also have an issue with the teleports, but different kind - it doesn't allow me to leave the teleport tile.

For example, at DooM 1 E2M1 there's a teleport right in the beginning - it teleports me to the destination just fine, but when I try to leave it teleports me back to the first room, and vice versa.

I've found a workaround for the first teleport on the level - leaving the teleport tile sideways does the trick. But this workaround won't work on a second one - there's simply no place to sidestep - only go forward.

The device I'm using is Trimui Smart Pro, with custom linux OS and GZDoom 4.13.2 .

**Comment by nickbailuc** [comment]
> I also have an issue with the teleports, but different kind - it doesn't allow me to leave the teleport tile.
> 
> For example, at DooM 1 E2M1 there's a teleport right in the beginning - it teleports me to the destination just fine, but when I try to leave it teleports me back to the first room, and vice versa.
> 
> I've found a workaround for the first teleport on the level - leaving the teleport tile sideways does the trick. But this workaround won't work on a second one - there's simply no place to sidestep - only go forward.
> 
> The device I'm using is Trimui Smart Pro, with custom linux OS and GZDoom 4.13.2 .

Hey, I've got the same result in E2M1, its the same issue! I'm guessing that device you listed is also ARM64?

**Comment by JeodC** [comment]
At the rate wsl compiles this, I'll have an answer for you for GCC tomorrow. For the record I compile on bullseye with `cmake -DNO_GTK=ON -DNO_FMOD=ON -DCMAKE_BUILD_TYPE=Release ..`, I assume the TrimUI comment above is similar if not the same, or they simply take the precompiled binary from the releases page.

**Comment by grobuzga** [comment]
> > I also have an issue with the teleports, but different kind - it doesn't allow me to leave the teleport tile.
> > For example, at DooM 1 E2M1 there's a teleport right in the beginning - it teleports me to the destination just fine, but when I try to leave it teleports me back to the first room, and vice versa.
> > I've found a workaround for the first teleport on the level - leaving the teleport tile sideways does the trick. But this workaround won't work on a second one - there's simply no place to sidestep - only go forward.
> > The device I'm using is Trimui Smart Pro, with custom linux OS and GZDoom 4.13.2 .
> 
> Hey, I've got the same result in E2M1, its the same issue! I'm guessing that device you listed is also ARM64?

Yes, the device runs 64bit linux system.

**Comment by arkadijs** [comment]
I've rebuild GZDoom 4.14.1 with gcc version 13.3.0 (Ubuntu 13.3.0-6ubuntu2~24.04)  on arm64 machine and it works just fine with teleports. Seems the problem is limited to the binary release / old compiler.

> cmake -B build -DCMAKE_BUILD_TYPE=Release

ZMusic master, otherwise pretty standard Ubuntu on Orange Pi 5.

**Comment by RicardoLuis0** [comment]
will be closing this then since it's a either compiler bug or fixed in 4.14.1

**Comment by arkadijs** [comment]
Yet the project released `gzdoom` binary for arm64 is still broken. https://github.com/ZDoom/gzdoom/releases/download/g4.14.1/gzdoom_4.14.1_arm64.deb

**Comment by Blzut3** [comment]
After analysis it turns out that this is caused by a strict aliasing violation in the TVector code.  GCC 14 doing the right thing is probably just a coincidence with the optimizer making different choices.  I should be able to put together a real fix soon.

**Comment by Blzut3** [comment]
Fixed with change set 6481f8cce909bc801f7544d67f2bf5f96cd01181.  New Linux binaries will be published soon whether that looks like 4.14.1 rebuilt with different optimization flags or a new release.

**Comment by cizia64** [comment]
4.14.1 wasn't OK, but 4.14.2 seems to work correctly with teleports (tested on TrimUI Smart Pro (arm64) with Legend of Doom and in Doom II E1M2, at the teleporter located besides the red key). Thank you for the fix @Blzut3  !
