### ISSUE TITLE
[BUG] Crash when opening scoreboard in a Teamplay Multiplayer Game

### ISSUE THREAD

**Issue by ohyesss** [ZDoom/gzdoom#3011]
### GZDoom version

4.14.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Ubuntu 24.04.2 64-Bit

### Relevant hardware info

AMD Ryzen 7 5800X 8-Core Processor × 16, NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

A crash frequently occurs, when opening the scoreboard in a game with other players/bots, while teamplay is set to true.
This also means that dying will crash the game as well, since dying opens the scoreboard.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Enter any map
2. Add any amount of bots
3. Set Teamplay to true
4. Open the scoreboard via Key or Death

### Your configuration

```ini

```

**Comment by nashmuhandes** [comment]
Fixed in https://github.com/ZDoom/gzdoom/commit/d33df9dba8f8bd97a254e461c076eb5e42ffad37

**Comment by ohyesss** [comment]
Has this crash fix been added?
I'm still getting crashes from opening the scoreboard with teamplay and 1 bot

**Comment by RicardoLuis0** [comment]
on devbuilds or on 4.14.2? i might've forgotten to include the fix for 4.14.2 unfortunately
